/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicRssDotxmlRouteImport } from './routes/api/public/rss[.]xml'
import { Route as ApiPublicRobotsDottxtRouteImport } from './routes/api/public/robots[.]txt'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRssDotxmlRoute = ApiPublicRssDotxmlRouteImport.update({
  id: '/api/public/rss.xml',
  path: '/api/public/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsDottxtRoute = ApiPublicRobotsDottxtRouteImport.update({
  id: '/api/public/robots.txt',
  path: '/api/public/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/search'
    | '/article/$id'
    | '/category/$slug'
    | '/api/public/robots.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/search'
    | '/article/$id'
    | '/category/$slug'
    | '/api/public/robots.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/search'
    | '/article/$id'
    | '/category/$slug'
    | '/api/public/robots.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  SearchRoute: typeof SearchRoute
  ArticleIdRoute: typeof ArticleIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ApiPublicRobotsDottxtRoute: typeof ApiPublicRobotsDottxtRoute
  ApiPublicRssDotxmlRoute: typeof ApiPublicRssDotxmlRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss.xml': {
      id: '/api/public/rss.xml'
      path: '/api/public/rss.xml'
      fullPath: '/api/public/rss.xml'
      preLoaderRoute: typeof ApiPublicRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots.txt': {
      id: '/api/public/robots.txt'
      path: '/api/public/robots.txt'
      fullPath: '/api/public/robots.txt'
      preLoaderRoute: typeof ApiPublicRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  SearchRoute: SearchRoute,
  ArticleIdRoute: ArticleIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  ApiPublicRobotsDottxtRoute: ApiPublicRobotsDottxtRoute,
  ApiPublicRssDotxmlRoute: ApiPublicRssDotxmlRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
